import { Users } from '../main/types';

var UserDB: Users = {
  1: {
    id: 1,
    name: 'Admin One',
    email: 'admin1@abc.com',
    role: 'ADMIN',
    prId: '',
  },
  2: {
    id: 2,
    name: 'Admin Two',
    email: 'admin2@abc.com',
    role: 'ADMIN',
    prId: '',
  },
  3: {
    id: 3,
    name: 'Employee One',
    email: 'emp1@abc.com',
    role: 'USER',
    prId: '',
  },
  4: {
    id: 4,
    name: 'Employee Two',
    email: 'emp2@abc.com',
    role: 'USER',
    prId: '',
  },
  5: {
    id: 5,
    name: 'Employee Three',
    email: 'emp3@abc.com',
    role: 'USER',
    prId: '1',
  },
  6: {
    id: 6,
    name: 'Employee Four',
    email: 'emp4@abc.com',
    role: 'USER',
    prId: '2',
  },
  7: {
    id: 7,
    name: 'Employee Five',
    email: 'emp5@abc.com',
    role: 'USER',
    prId: '3',
  },
  9: {
    id: 9,
    name: 'Employee Six',
    email: 'emp6@abc.com',
    role: 'USER',
    prId: '4',
  },
  10: {
    id: 10,
    name: 'Employee Seven',
    email: 'emp7@abc.com',
    role: 'USER',
    prId: '5',
  },
  11: {
    id: 11,
    name: 'Employee Eight',
    email: 'emp8@abc.com',
    role: 'USER',
    prId: '6',
  },
  12: {
    id: 12,
    name: 'Employee Nine',
    email: 'emp9@abc.com',
    role: 'USER',
    prId: '7',
  },
  13: {
    id: 13,
    name: 'Employee Ten',
    email: 'emp10@abc.com',
    role: 'USER',
    prId: '8',
  },
  14: {
    id: 14,
    name: 'Employee Eleven',
    email: 'emp11@abc.com',
    role: 'USER',
    prId: '9',
  },
  15: {
    id: 15,
    name: 'Employee Twelve',
    email: 'emp12@abc.com',
    role: 'USER',
    prId: '10',
  },
  16: {
    id: 16,
    name: 'Employee Thirteen',
    email: 'emp13@abc.com',
    role: 'USER',
    prId: '11',
  },
  17: {
    id: 17,
    name: 'Employee Fourteen',
    email: 'emp14@abc.com',
    role: 'USER',
    prId: '12',
  },
  18: {
    id: 18,
    name: 'Employee Fifteen',
    email: 'emp15@abc.com',
    role: 'USER',
    prId: '',
  },
  19: {
    id: 19,
    name: 'Employee Sixteen',
    email: 'emp16@abc.com',
    role: 'USER',
    prId: '',
  },
};

export default UserDB;
